version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: vrdev.azurecr.io/api:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1
